
workspace : "/tmp/layers"

interface: ens33

worker_thread: 4

dissector:
  - http
  - smb

skip_http_content_key:
  - txt
  - html
  - json
  - js
  - text
  - javascript
#  - png
#  - jpg
#  - jpeg
#  - image